spring:
  envTemp: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis2?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  #引用其他的yaml文件时
  #profiles:
    #include: tmp
